name: 'qnxt_edp'
version: '1.0.0'
config-version: 2

profile: 'qnxt_edp'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  # Source database and schema configuration
  qnxt_database: 'PLAYGROUND'
  qnxt_schema: 'BRONZE_RAW_QNXT'  # Seeds load here via generate_schema_name

  # MDM source configuration
  mdm_database: 'PLAYGROUND'
  mdm_schema: 'RAW_MDM'

  # Target schema configuration for medallion layers
  bronze_schema: 'BRONZE'
  silver_schema: 'SILVER'
  gold_schema: 'GOLD'

models:
  qnxt_edp:
    # Staging models (Bronze layer)
    staging:
      +schema: bronze
      +materialized: view
      +tags: ['bronze', 'staging']

      # MDM staging models
      mdm:
        +tags: ['bronze', 'staging', 'mdm']

    # Marts (Silver and Gold layers)
    marts:
      core:
        +schema: silver
        +materialized: table
        +tags: ['silver', 'core']
      claims:
        +schema: gold
        +materialized: table
        +tags: ['gold', 'claims']
      membership:
        +schema: gold
        +materialized: table
        +tags: ['gold', 'membership']
      finance:
        +schema: gold
        +materialized: table
        +tags: ['gold', 'finance']

seeds:
  qnxt_edp:
    +schema: silver
    # Source table seeds - load to RAW_QNXT schema (becomes BRONZE_RAW_QNXT via generate_schema_name)
    sample_claims:
      +schema: RAW_QNXT
      +alias: clclaim
    sample_claim_lines:
      +schema: RAW_QNXT
      +alias: clline
    sample_members:
      +schema: RAW_QNXT
      +alias: member
    sample_providers:
      +schema: RAW_QNXT
      +alias: provider
    sample_cldiag:
      +schema: RAW_QNXT
      +alias: cldiag
    sample_clproc:
      +schema: RAW_QNXT
      +alias: clproc
    sample_cladjust:
      +schema: RAW_QNXT
      +alias: cladjust
    sample_proccode:
      +schema: RAW_QNXT
      +alias: proccode
    sample_mbrelig:
      +schema: RAW_QNXT
      +alias: mbrelig
    sample_diagcode:
      +schema: RAW_QNXT
      +alias: diagcode

    # MDM seeds - load to RAW_MDM schema for local testing
    mdm_golden_member:
      +schema: RAW_MDM
      +alias: golden_member
    mdm_golden_provider:
      +schema: RAW_MDM
      +alias: golden_provider
    mdm_member_crosswalk:
      +schema: RAW_MDM
      +alias: member_crosswalk
      +column_types:
        effective_date: date
        termination_date: date
    mdm_provider_crosswalk:
      +schema: RAW_MDM
      +alias: provider_crosswalk
      +column_types:
        effective_date: date
        termination_date: date

snapshots:
  qnxt_edp:
    +schema: silver
    +strategy: timestamp
    +updated_at: updated_at

